services:
  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
    container_name: test_db
    ports:
      - "5432:5432"
